### ISSUE TITLE
job recurring

### ISSUE THREAD

**Issue by valantis315** [peppeocchi/php-cron-scheduler#110]
Hi there,

I have scheduled a job for daily use and works fine, however, there is a need to run some other jobs weekly, monthly and yearly.
Is there this functionality?
For example, can I schedule the below jobs? Will be executed?
$scheduler->php(__DIR__.'/assets/scripts/dailyaggregation.php')->daily();
$scheduler->php(__DIR__.'/assets/scripts/weeklyaggregation.php')->weekly();
$scheduler->php(__DIR__.'/assets/scripts/monthlyaggregation.php')->monthly();
$scheduler->php(__DIR__.'/assets/scripts/yearlyaggregation.php')->yearly();

Thank you

**Comment by cetric32** [comment]
Yes, they will be executed
