### ISSUE TITLE
How to do a job once?

### ISSUE THREAD

**Issue by rtanzifi** [peppeocchi/php-cron-scheduler#111]
Hi. can i run a job just once at specific time with seconds? for Example 2020-08-31 20:30:59?

**Comment by peppeocchi** [comment]
Hi, please have a look at the documentation [here](https://github.com/peppeocchi/php-cron-scheduler#schedules-execution-time), you can specify a date for when the job should run

```
$scheduler->php('script.php')->date('2020-08-31 20:30');
```

Please note that with cronjobs you can't specify seconds.
There are workaround that go beyond the purpose of this library. https://unix.stackexchange.com/questions/11102/cron-running-job-every-15-seconds
