### ISSUE TITLE
Jobs are not executing asynchronously

### ISSUE THREAD

**Issue by aliforever** [peppeocchi/php-cron-scheduler#12]
Hey, thanks for the effort.
Was wondering if the scheduler supports running php files asynchronously?
As far as I understood, it is waiting for a job to finish and then moves on to the next one, 
So if I have set 10 crawlers to run every minute, it will timeout on first one that takes a minute.
Thanks again

**Comment by peppeocchi** [comment]
@aliforever by default all the jobs will run in background.
The only exception is when you schedule a function, or when you specify that the job should run in foreground with `$scheduler->php('myFile')->runInForeground()->every()->minute();`

Jobs that can run in background are being [executed](https://github.com/peppeocchi/php-cron-scheduler/blob/master/src/GO/Job/Job.php#L390) with an [&](https://github.com/peppeocchi/php-cron-scheduler/blob/master/src/GO/Job/Job.php#L333) at the end of the command.

**Comment by aliforever** [comment]
Thanks for the response.
Right, that's weird to me, because when I add the crawlers inside the cron jobs, they all run together and it takes 5 minutes to get the result I want, but running them with the scheduler, I don't get the same result.

```
$scheduler->php(__DIR__.'/likefetchers/fetcher1.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob1.log');
$scheduler->php(__DIR__.'/likefetchers/fetcher2.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob2.log');
$scheduler->php(__DIR__.'/likefetchers/fetcher3.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob3.log');
$scheduler->php(__DIR__.'/likefetchers/fetcher4.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob4.log');
$scheduler->php(__DIR__.'/likefetchers/fetcher5.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob5.log');
$scheduler->php(__DIR__.'/likefetchers/fetcher6.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob6.log');
$scheduler->php(__DIR__.'/likefetchers/fetcher7.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob7.log');
$scheduler->php(__DIR__.'/likefetchers/fetcher8.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob8.log');
$scheduler->php(__DIR__.'/likefetchers/fetcher9.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob9.log');
$scheduler->php(__DIR__.'/likefetchers/fetcher10.php')->at('* * * * *')->output(__DIR__.'/likefetchers/cronjob10.log');
$scheduler->run();
```
These are the jobs. 
I'll check further to find out if there are any issues inside the scripts.
Thanks again.

**Comment by peppeocchi** [comment]
@aliforever I just released a [v2](https://github.com/peppeocchi/php-cron-scheduler/releases/tag/v2.0) of the Scheduler, the library has been rewritten (almost) from scratch, it is now fully tested, please have a look at the [readme](https://github.com/peppeocchi/php-cron-scheduler/blob/master/README.md) if you wish to update to this release.

Tests confirm that jobs that can run in background will not wait and are prioritised over jobs in foreground.

If you feel that this is still an issue, please reopen it and provide a use case that will fail the tests.

**Comment by adarmanto** [comment]
Hello @peppeocchi, I used the latest version@2.3.2. It looks that if a job that can run in background will not actually fire `then($callback, true)` after job execution?

```
// Create a new scheduler
$scheduler = new Scheduler();
$scheduler
	->raw('php -r "sleep(rand(5,10)); echo \'Executed\';"', [], 1)
	->at('* * * * * ')
	->before(function(){
		echo '1. Started running at ' . date('Y-m-d H:i:s') . ' ...' . PHP_EOL;
	})
	->then(function($output) {
		echo '1. Finished at ' . date('Y-m-d H:i:s') . PHP_EOL;
	}, true);

$scheduler
	->raw('php -r "sleep(rand(5,10)); echo \'Executed\';"', [], 2)
	->at('* * * * * ')
	->before(function(){
		echo '2. Started running at ' . date('Y-m-d H:i:s') . ' ...' . PHP_EOL;
	})
	->then(function($output) {
		echo '2. Finished at ' . date('Y-m-d H:i:s') . PHP_EOL;
	}, true);

$scheduler
	->raw('php -r "sleep(rand(5,10)); echo \'Executed\';"', [], 3)
	->at('* * * * * ')
	->before(function(){
		echo '3. Started running at ' . date('Y-m-d H:i:s') . ' ...' . PHP_EOL;
	})
	->then(function($output) {
		echo '3. Finished at ' . date('Y-m-d H:i:s') . PHP_EOL;
	}, true);

// Let the scheduler execute jobs which are due.
$scheduler->run();
```
Output:

> 1. Started running at 2018-05-10 22:49:11 ...
> 1. Finished at 2018-05-10 22:49:11
> 2. Started running at 2018-05-10 22:49:11 ...
> 2. Finished at 2018-05-10 22:49:11
> 3. Started running at 2018-05-10 22:49:11 ...
> 3. Finished at 2018-05-10 22:49:11
