### ISSUE TITLE
Upgrade for php version 8.1

### ISSUE THREAD

**Issue by Wernke96** [peppeocchi/php-cron-scheduler#133]
will there be and upgrade release for version 8.1.

**Comment by peppeocchi** [comment]
@Wernke96 I just [tested the code with php8.1](https://github.com/peppeocchi/php-cron-scheduler/runs/5768084450?check_suite_focus=true) and all testing are passing OK, are you seeing any issue on your end when trying to install/use it in your projects requiring php 8.1?
