### ISSUE TITLE
The After method can not be accessed

### ISSUE THREAD

**Issue by elvispdosreis** [peppeocchi/php-cron-scheduler#16]
The **after** method is not available for access by php

using "peppeocchi/php-cron-scheduler": "^2.0"

$scheduler->php('script.php')->**after**(function ($output) use ($logger, $messenger) {
    $logger->info($output);
    $messenger->ping('myurl.com', $output);
});

**Comment by peppeocchi** [comment]
@elvispdosreis sorry it's a typo in the documentation, the actual method name is `then`

https://github.com/peppeocchi/php-cron-scheduler/blob/master/src/GO/Job.php#L524

```php
$scheduler->php('script.php')->then(function ($output) use ($logger, $messenger) {
    $logger->info($output);
    $messenger->ping('myurl.com', $output);
});
```

I'll fix the documentation, thanks
