### ISSUE TITLE
exception 'InvalidArgumentException' with message 'There are no commands defined in the "xxx" namespace.' 

### ISSUE THREAD

**Issue by susanBuck** [peppeocchi/php-cron-scheduler#2]
Was getting this exception when commands were triggered via cron/php-cron-scheduler, but not when I ran them manually.

Found this thread detailing the same issue, but with Dispatcher.

My solution w/ php-cron-scheduler was to specify `usr/bin/php-cli` instead of `php` in the cron command:

So this:
`php /home/thewcc/www/abc/artisan "abc:run-all-scheduled-jobs" > /dev/null`

Became this:
`/usr/bin/php-cli /home/thewcc/www/abc/artisan "abc:run-all-scheduled-jobs" > /dev/null`

Noting here just in case anyone else comes across a similar problem.

**Comment by peppeocchi** [comment]
@susanBuck thanks for pointing that out, it's the first time I see that problem.

There is a workaround to that issue (I found that using vanilla aws elastic beanstalk some system variables are not set), so there is a method to set the path to your php bin with
```php
...
$scheduler->php('file')->useBin('path/to/my/php/bin')->at(....)
...
```

or you can set that directly [here](https://github.com/peppeocchi/php-cron-scheduler/blob/master/src/GO/Job/Php.php#L22)

Hope that helps!
