### ISSUE TITLE
Swiftmailer 6.0 compatibility

### ISSUE THREAD

**Issue by nforced** [peppeocchi/php-cron-scheduler#20]
Will there be support for Swiftmailer >=6.0?
I ran into this issue https://github.com/yiisoft/yii2/issues/7848 and had to use 5.4.0 to make it work.

**Comment by nforced** [comment]
Great! 
I just want to remind you that this will break backward compatibility for users still using 5.4. Maybe additional check for newInstance() method existence will help but that's up to you. 

Thanks a lot for the quick response!

**Comment by peppeocchi** [comment]
@nforced I actually tested with both 5.4 and 6.0, the difference between the two versions is the method `newInstance` being removed, but the classes can still be instantiated as usual.

In v5.4 the following code is equally valid
```php
$transport = \Swift_MailTransport::newInstance();
$transport = new \Swift_SendmailTransport();
```

phpunit tests are passing with both versions, it should be ok ;)

Thank you for pointing that out!
