### ISSUE TITLE
->then is called immediately when a job is run and not after the job ends

### ISSUE THREAD

**Issue by adamwinn** [peppeocchi/php-cron-scheduler#31]
I have a job that takes 10 secs before it finishes.  When I call `->then(function ($output)` that function is called immediately and not after the job has finished 10 secs later.

The first thing I do in the `->then(function ($output)` function is write the time and it's always something like `2017-10-03 07:14:00`, not `2017-10-03 07:14:10`

Also, my job produces stdout but `$output` is always null.

**Comment by peppeocchi** [comment]
Hi @adamwinn the `then` method accepts a second parameter (boolean) that allows you to run the job async, and not to wait for the output. Are you sure you are not passing that parameter as `true`?
That would explain the behaviour you're seeing.

[This test](https://github.com/peppeocchi/php-cron-scheduler/blob/master/tests/GO/JobTest.php#L356) ensures the method waits for the job to be complete.

Can you please paste that block of code here?

**Comment by adamwinn** [comment]
I just took the code from the examples on the home page.

```
$scheduler->raw($command)
        ->daily($time)
        ->when(function () use ($type) {
            return get_when($type);
        })
        ->then(function ($output) use ($name)  {
		//do stuff
        }, true);
```

**Comment by adamwinn** [comment]
It doesn't appear as if you can get a status update upon execution and a status update upon completion

```
->then(function ($output) use ($name)  {
     //job started
  }, true)
->then(function ($output) use ($name)  {
    //job ended
 });

**Comment by adamwinn** [comment]
Also, if I do
```
->then(function ($output) use ($name) {
       file_put_contents(__DIR__.'/output.log', print_r($output,1), FILE_APPEND);
   })
```
and my output.log has 
```
Array
(
)
```
and the contents of `$output` goes to my system mailbox instead

**Comment by peppeocchi** [comment]
@adamwinn thank you for your feedback, I think you are reporting different things here let me make things clear.

- Passing **true** as a second parameter to the `then` method will execute the job in background (so the output will be null as in the block of code you pasted as a reply). [This is the documentation](https://github.com/peppeocchi/php-cron-scheduler#after-job-execution) that explains how to use it.
- That's correct, there is no `before` method built in, this could be a feature request if you want to propose a PR, so you should handle that in your job (script/function), unless you are not in control of the scheduled job. So, to be clear, the `then` method will be called only **after** your job is being executed.
- It's really hard to tell you why your output is not being sent to your log without looking at your code. What should be the output you expect? Just keep in mind that the expected output should be a string or any other type that can be converted to a string (or object that implements the `__toString` [method](http://php.net/manual/it/language.oop5.magic.php#object.tostring)). The output of your job is being intercepted as **output buffer**.
I did a few tests and the output was as expected, please test this code
```php
$scheduler->call(function () {
    echo "I will be in your output log";

    return [
        "no" => "This return will be printed in your log as Array()",
        "yes" => "If you return the array as json, I will be in your output!",
    ];
    // example of correct return printed in output.log would be
    // return json_encode(['my' => 'array']);
})->then(function ($output) {
    file_put_contents(__DIR__.'/output.log', print_r($output, 1), FILE_APPEND);
});
```

It would be helpful if you could paste here your script code, but I think it's not an issue with the scheduler itself but an issue with the documentation that could be more clear of what to expect.

**Comment by peppeocchi** [comment]
@adamwinn there is now a `before` method you can use before the job runs
Please read more in #32 

I'll close this issue for now, feel free to reopen it if you think there is an issue with the scheduler, thank you
