### ISSUE TITLE
Implement "before" method

### ISSUE THREAD

**Issue by peppeocchi** [peppeocchi/php-cron-scheduler#32]
The scheduler currently supports a `then` method, a callback executed after the job runs.

It seems a good idea to have a `before` method that's being executed before the job runs.

**Comment by JordanRL** [comment]
Should this `before` method receive that args supplied? Should the output be piped?

**Comment by peppeocchi** [comment]
The purpose of this method should be of executing a function just before the job runs (e.g. write a log line, ping a URL etc...), the same purpose of the `then` method.
To answer your questions: no argument is required, a nice to have would be to pass the name of the job and other relevant information, but those could be implemented later on. There is no plan currently on using the output of this function, but I am open to discussion if you think it would be useful.

**Comment by JordanRL** [comment]
Alright. The reason I asked is that the `then` method takes the output as an argument. I am naming the private property to `$berfore` and the method call `first`.

**Comment by JordanRL** [comment]
Ah, but I'll only finish my implementation if you need something other than what emptyhand did. :)

**Comment by peppeocchi** [comment]
@JordanRL thank you anyway, he was faster on sending the PR :)

**Comment by JordanRL** [comment]
Hey no problem! Glad to tackle some open source issues across github, I'm just glad to see PHP projects get attention.

**Comment by peppeocchi** [comment]
Closed with #33
