### ISSUE TITLE
Job will not fail if called php script not exists

### ISSUE THREAD

**Issue by lunar-rocket** [peppeocchi/php-cron-scheduler#35]
If you call `$scheduler->php('script.php');` and there is no script.php present, the job will be listed under executed jobs and not under failed jobs. Thats really bad.

**Comment by peppeocchi** [comment]
@lunar-rocket thanks for reporting the issue, I just made an hot fix and will release a new version in the next few minutes

**Comment by lunar-rocket** [comment]
:thumbsup:
