### ISSUE TITLE
Invalid script path - mark it as failed job

### ISSUE THREAD

**Issue by peppeocchi** [peppeocchi/php-cron-scheduler#37]
Currently when passing an invalid path for a job to the scheduler (php only), it is throwing an `InvalidArgumentException` straight away.

It would be a nice to have to instead of throwing the exception (and preventing other valid jobs to run) it will mark it as failed job and it will keep running the other jobs.
This is something already covered when scheduling Closures, so it should be handled only when scheduling `php` scripts.

**Comment by Harumaro** [comment]
Is this still up for grabs?

If so I have one question before I can send it: I noticed php and raw jobs are simply run thru exec, should this PR also apply this behavior to raw commands?

**Comment by Harumaro** [comment]
Tried to keep it as generic as possible, so in the future there might be room to also add a check on raw scripts running **which $command** in the _raw_ method.

**Comment by peppeocchi** [comment]
@Harumaro thank you for your contribution, @mbiagetti submitted a PR before yours, but I also understand you were probably already working on that.

To reply to your first question, there is no need to validate a script path when running `raw` commands because it could be anything and it's not clear how to understand if the raw command is executing a file. Anyway if someone schedules a raw command, it should also make sure his command is correct (with a valid file if required). The `Scheduler` class can also be extended to e.g. add a `python` method that executes a python script (and the same check can be added to that method).

I've reviewed both PRs, although @Harumaro your is interesting (as it will allow better flexibility when extending the class and not repeat checks that can be done at the Job level), I'll go for the one from @mbiagetti as it is what I was looking for.

**Comment by mbiagetti** [comment]
Hi @Harumaro sorry for the mistake: i didn't see your comment before submit my pr

**Comment by Harumaro** [comment]
No worries! Having choices is good for the sake of opensource, that's why I went on and submitted it anyway :)
