### ISSUE TITLE
Cron times in Seconds?

### ISSUE THREAD

**Issue by kristopherlarson** [peppeocchi/php-cron-scheduler#41]
Is it possible to setup a schedule to run every 10 seconds or lets say 30 seconds?

**Comment by peppeocchi** [comment]
Hi, unfortunately I don't think this is possible out of the box, the minimum interval for a cron is 1 minute (the scheduler will run every minute).

I suggest you to implement your own way of handling smaller intervals, one idea would be to pause the scheduler every 10 seconds (make sure all your jobs can run in background)
```php
$scheduler->php('somescript.php');

for ($i = 0; $i < 6; $i++) {
    $scheduler->run();
    sleep(10);
}
```

You can read more about multiple runs [here](https://github.com/peppeocchi/php-cron-scheduler#multiple-scheduler-runs).

**Comment by kristopherlarson** [comment]
Okay do you think I would run into any issues doing something like this? Memory leaks or anything.

**Comment by peppeocchi** [comment]
@kristopherlarson I don't think so, it really depends on what each job is doing. I would advice you to setup only background jobs that won't block the scheduler.
