### ISSUE TITLE
Does this support windows? if so, how does it achieve parallel tasks?

### ISSUE THREAD

**Issue by buddhika162** [peppeocchi/php-cron-scheduler#42]
It seems this is running tasks on the background to achieve parallelism. But does it work with windows?

**Comment by hpr0009** [comment]
I'd also like to know the answer to this...

**Comment by peppeocchi** [comment]
@buddhika162 @hpr0009 sorry guys this wasn't designed to work on windows so I am not sure about the answer. But if you try it please let me know (if it doesn't I'd be happy to review/accept your PR)
