### ISSUE TITLE
Cannot get email to be sent (version 2.3.1)

### ISSUE THREAD

**Issue by c5creative** [peppeocchi/php-cron-scheduler#44]
Greetings,

I've been turning this problem sideways for the last few hours and hope someone can point out the obvious to me.

Overall, the scheduler works fine. However, I cannot seem to get emails to be sent. Here is my script, which I know is being executed since it's running the scheduled PHP script. I've also tested out the Swift_SmtpTransport (which is why it's abstracted out below), which does send out email successfully using the same parameters.

Any advice would be appreciated. Cheers!
JP

```php
require_once __DIR__.'/vendor/autoload.php';

use GO\Scheduler;

// Create the Transport the call setUsername() and setPassword()
$transport = (new Swift_SmtpTransport('mail.***.com', 789, 'ssl'))
    ->setUsername('scheduler@***.com')
    ->setPassword('***');

$scheduler = new Scheduler([
    'email' => [
        'subject' => 'croncron',
        'from' => 'scheduler@***.com',
        'body' => 'This is the email body',
        'transport' => $transport
    ]
]);

// ... configure the scheduled jobs (see below) ...
$scheduler->php(
    '/absolute/path-to-script.php', // The script to execute
    '/usr/local/bin/php', // The PHP bin
    [
        '--account' => '1'
    ],
    'IdScheduler'
)
    ->everyMinute()
    ->email(['***@***.com']);


// Let the scheduler execute jobs which are due.
$scheduler->run();
```

**Comment by peppeocchi** [comment]
@c5creative in order to [send the output of your schedules](https://github.com/peppeocchi/php-cron-scheduler#send-output-to-emails) to an email address, you need to save that output to a file (the file is then being attached to the email you'll receive)

So your code should look like
```php
// ... configure the scheduled jobs (see below) ...
$scheduler->php(
    '/absolute/path-to-script.php', // The script to execute
    '/usr/local/bin/php', // The PHP bin
    [
        '--account' => '1'
    ],
    'IdScheduler'
)
    ->everyMinute() // You can omit this line, by default if not specified your job is scheduled to run every minute
    ->output('path/to/my/file.txt') // This is what you need
    ->email(['***@***.com']);
```

**PS:** thanks to this issue I found another issue related to mail transport (already being fixed [here](https://github.com/peppeocchi/php-cron-scheduler/releases/tag/v2.3.2))
