### ISSUE TITLE
Scheduling at a precise date and time = one shot run

### ISSUE THREAD

**Issue by lmartones** [peppeocchi/php-cron-scheduler#46]
Hey there,

Is it possible to run a job at a precise datetime, please ? I would like to use my scheduler for deferred production deployment.

Many thanks

**Comment by peppeocchi** [comment]
Hi, that feature is not supported out of the box, but it shouldn't be difficult to implement it using the scheduler.
You can check if the current date and time matches your deployment time, in this case you would schedule your task. By default the task is set to run every minute, so just by scheduling your task it will trigger a run.
I don't know how you're pulling the deployment datetime, but something like this should work fine

```php
$deploymentTime = '2018-02-01 00:00:00';

if ($deploymentTime === date('Y-m-d H:i:s')) {
    $scheduler->php('/path/to/my/script.php'); // By default this runs every minute
}

$scheduler->run();
```

Of course you can use whatever method you like to check if your deployment time matches the current date and time.

I'll close this issue for now, it could be a nice feature to add though.

**Comment by peppeocchi** [comment]
@lmartones I'll probably include that feature in the next release ;)

**Comment by lmartones** [comment]
Ahh great news thanks alot :)
