### ISSUE TITLE
No overlapping jobs

### ISSUE THREAD

**Issue by blackburn1911** [peppeocchi/php-cron-scheduler#5]
Hi,

Very nice package. Can you add an option to avoid overlapping a job?

**Comment by peppeocchi** [comment]
Hi @blackburn1911 

the new version I just released has a `doNotOverlap()` function that you can set when scheduling a job.
You can optionally pass a callback to allow the job to overlap if you need to. You can read more [here](https://github.com/peppeocchi/php-cron-scheduler/blob/master/README.md#job-overlapping).

Thanks for the tip, it's a nice feature 👍
