### ISSUE TITLE
No email when empty output

### ISSUE THREAD

**Issue by rafal-sokolowski** [peppeocchi/php-cron-scheduler#56]
I use the scheduler to run error reporting cron jobs. It means an output is generated only if there's an error and only then an email should be sent.

Could you add a setting/property/method which skips sending an email when there's no output given?

**Comment by peppeocchi** [comment]
Hi @rafal-sokolowski I've now added a new setting to skip sending the email if there is no output.
As usual, you can set it as global or it can be different for each scheduled job.

```php
$scheduler = new Scheduler([
    'email' => [
        'subject' => 'Visitors count',
        'ignore_empty_output' => true,
    ]
]);
```
