### ISSUE TITLE
how to setup SMTP server for email

### ISSUE THREAD

**Issue by smartbackend** [peppeocchi/php-cron-scheduler#6]
I think it's swift message, could you add SMTP settings on config ?

**Comment by elvispdosreis** [comment]
As an SMTP configurator would be welcome, since we often do not open the log files to look for errors.

**Comment by peppeocchi** [comment]
Thanks, I made the changes to accept common mail settings (host, port, username, password).
I just need to do some testing and then I'll publish a new release.

**Comment by peppeocchi** [comment]
@smartbackend this is now supported in [v2](https://github.com/peppeocchi/php-cron-scheduler/releases/tag/v2.0), please have a look at the [readme](https://github.com/peppeocchi/php-cron-scheduler/blob/master/README.md#send-output-to-emails) on how to customise your SMTP configuration.
