### ISSUE TITLE
How to call method of another object

### ISSUE THREAD

**Issue by developer99** [peppeocchi/php-cron-scheduler#7]
Is there a way to call the method of the current object or another object?

Thanks for a pretty cool, easy-to-use, scheduler.

**Comment by peppeocchi** [comment]
@developer99 thank you!

What are you exactly trying to do?

**Comment by developer99** [comment]
Well I have the scheduler included in a MVC framework.  And the scheduler code is in a controller method.  I will likely create scripts for the scheduler to execute using a scriptFactory method that creates the scriptJob class which I would like to call from the scheduler.

so I want to do something like...

`
$newjob = new ScriptFactory('monitor');
$scheduler->call('$newjob->run()')->every()->day('22:51')->output($f3->get('LOGS') . 'call_time.log');
`
OR

`
// Use the __invoke magic method which makes an object callable.
$scheduler->call('$newjob')->every()->day('22:51')->output($f3->get('LOGS') . 'call_time.log');
`

I ended up creating a separate controller for the jobscript and used a raw command to run curl on a route that would invoke the job.  Seems to work ok.

**Comment by peppeocchi** [comment]
@developer99 
The `call` method accepts a [Closure](http://php.net/manual/en/functions.anonymous.php) that can inherit variables from the parent scope (so you can pass your dynamic scriptJob to the anonymous function).
```php
$newjob = new ScriptFactory('monitor');

$scheduler->call(function () use ($newjob) {
    $newjob->run();
})->every()->day('22:51')->output($f3->get('LOGS') . 'call_time.log');
```
would something like that suits you? do you want to give it a go?

**Comment by developer99** [comment]
Ah.  Cool.  Yes. that would work I suppose.  Didn't think about that.  Thank you very much.  Next time I setup a job I will try it.  Thanks.
