### ISSUE TITLE
Ability to cancel a job before it's being executed

### ISSUE THREAD

**Issue by rafal-sokolowski** [peppeocchi/php-cron-scheduler#71]
I'd be quite handy to have the ability to prevent a job from being executed if the condition in `before` method it's not met.

**Comment by peppeocchi** [comment]
Hi @rafal-sokolowski you can accomplish the same thing by chaining the `when` method to you job schedule https://github.com/peppeocchi/php-cron-scheduler#schedule-conditional-execution, the `before` method is meant to do something before the job runs (e.g. writing to a log file).

Feel free to reopen this issue if this doesn't work for you.
