### ISSUE TITLE
 Class 'GO\Scheduler' not found

### ISSUE THREAD

**Issue by afaqahmedkhan** [peppeocchi/php-cron-scheduler#79]
I'm facing this issue, I'm a newbie to php, help needed 

PHP Fatal error:  Uncaught Error: Class 'GO\Scheduler' not found in D:\scheduler.php:6
Stack trace:
#0 D:\test.php(9): include()
#1 {main}
  thrown in D:\scheduler.php on line 6

Fatal error: Uncaught Error: Class 'GO\Scheduler' not found in D:\scheduler.php:6
Stack trace:
#0 D:\test.php(9): include()
#1 {main}
  thrown in D:\scheduler.php on line 6

**Comment by peppeocchi** [comment]
@afaqahmedkhan I am closing this, you should make sure you've correctly included the composer autoload file
