### ISSUE TITLE
Commands are not being run

### ISSUE THREAD

**Issue by awalls** [peppeocchi/php-cron-scheduler#8]
I have the following set up in a PHP class:

    class Cron {
        public function run() {
            $config = [
                "emailFrom" => "cron@example.com",
                "emailTo" => "me@example.com"
            ];
      
            $scheduler = new Scheduler($config);  
            $scheduler->call('myFunc')->every()->minute()->output(APPPATH .'logs/cron.log');
        }
    
        function myFunc() {
            echo 'Message called from cron');
        }
    }

I have a cron setup to call this every minute, however myFunc() never gets called. I can see a run method in the Scheduler class which never gets called. Am I missing something obvious in my setup?

**Comment by peppeocchi** [comment]
Hi, you need to run the scheduler at the end of your run function. Just add `$scheduler->run()` after you have defined your schedules.
