### ISSUE TITLE
Arguments passing

### ISSUE THREAD

**Issue by Sandbird** [peppeocchi/php-cron-scheduler#88]
How exactly can you pass arguments to the script ? The documentation doesn't make sense
```
    [
        '-c' => 'ignore',
        '--merge' => null,
    ],
```
What are these ? POST, GET ? I've tried different combos, nothing worked.
Also what's the 'identifier' for ?
-ty

**Comment by Sandbird** [comment]
You need to enable **register_argc_argv** in php .ini for arguments to work

**Comment by peppeocchi** [comment]
@Sandbird you're right about the **register_argc_argv** to be enabled, but it's also true that it is enabled by default so you have intentionally disabled it for some reason (or being on a host where it's disabled by default).
I'll add it to the documentation anyway, thanks.
