### ISSUE TITLE
Jobs that call the same PHP files, but with different parameters, have the same job ID generated, based only on the name of the script.

### ISSUE THREAD

**Issue by phinor** [peppeocchi/php-cron-scheduler#95]
# Environment

- PHP 7.2
- `composer require peppeocchi/php-cron-scheduler:^3.0`

# How to reproduce
```
$scheduler = new \GO\Scheduler();
$scheduler->php("backup.php", null, ['--type' => 'monthly'])->monthly();
$scheduler->php("backup.php", null, ['--type' => 'weekly'])->weekly();
$scheduler->php("backup.php", null, ['--type' => 'daily'])->daily();
$jobs = $scheduler->getQueuedJobs ();
/** @var \GO\Job $job */
foreach ($jobs as $job)
{
    echo $job->getId()."<br>";
}
```

# Expected Behaviour
Each job gets its own unique ID, differentiated by the parameters.

# Observed Behaviour
The three jobs share the same ID.

# Possible Solutions
The Job ID is created using a hash that takes into account the first two parameters that are passed to the `\GO\Job` constructor (i.e. `$command` and `$args`), while allowing the ID to be overridden by the supplied identifier, if any.

**Comment by peppeocchi** [comment]
@phinor thank you for the PR, it's now merged so I'll close this issue
